languageCode = "en"
title = "Matteo Cervelli"
theme = "ananke"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
enableGitInfo = true

[languages]
    [languages.en]
        contentDir = "content/en"
        disabled = false
        languageCode = "en-US"
        languageDirection = "ltr"
        languageName = "English"
        title = "Matteo Cervelli"
        weight = 1
        [languages.en.params]
            subtitle = "Business Growth Engineer"
    [languages.it]
        contentDir = "content/it"
        disabled = false
        languageCode = "it-IT"
        languageDirection = "ltr"
        languageName = "Italian"
        title = "Matteo Cervelli"
        weight = 2
        [languages.it.params]
            subtitle = "Ingegnere della Crescita delle Imprese"

[languages.en.menus]
    [[languages.en.menus.main]]
        name = "About"
        url = "/en/about/"
        weight = 1
    [[languages.en.menus.main]]
        name = "Posts"
        url = "/en/posts/"
        weight = 2
    [[languages.en.menus.main]]
        name = "Work"
        url = "/en/work/"
        weight = 3
    [[languages.en.menus.main]]
        name = "Newsletter"
        url = "/en/newsletter/"
        weight = 4

[languages.it.menus]
    [[languages.it.menus.main]]
        name = "Su di me"
        url = "/it/about/"
        weight = 1
    [[languages.it.menus.main]]
        name = "Articoli"
        url = "/it/posts/"
        weight = 2
    [[languages.it.menus.main]]
        name = "Lavoro"
        url = "/it/lavora-con-me/"
        weight = 3
    [[languages.it.menus.main]]
        name = "Newsletter"
        url = "/it/newsletter/"
        weight = 4

[params]
    logo = "/images/MC extendend logo white.png"


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[permalinks] 
    posts = "/:slug"

[taxonomies]
    tag = 'tags'
    category = 'categories'

[module]
    [module.hugoVersion]
        extended = true
        min = "0.55.0"
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "static"
        target = "static"

[build]
  writeStats = true

[build.buildStats]
  enable = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "feed"
    isPlainText = true
    protocol = "https://"
    noUgly = true
  [outputFormats.CSS]
    mediaType = "text/css"
    baseName = "main"
    isPlainText = true
    notAlternative = true

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ["xml"]
  [mediaTypes."text/css"]
    suffixes = ["css"]

[services]
  [services.rss]
    limit = 20