baseURL = "https://matteocervelli.com"
languageCode = "en"
title = "Matteo Cervelli"
theme = "ananke"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
    [languages]
        [languages.en]
            contentDir = "content/en"
            disabled = false
            languageCode = "en-US"
            languageDirection = "ltr"
            languageName = "English"
            title = "Matteo Cervelli"
            weight = 1
            [languages.en.params]
                subtitle = "Business Growth Engineer"
        [languages.en.menus]
            [[languages.en.menus.main]]
                name = "About"
                url = "/en/about/"
                weight = 1
            [[languages.en.menus.main]]
                name = "Posts"
                url = "/en/posts/"
                weight = 2
            [[languages.en.menus.main]]
                name = "Work"
                url = "/en/work/"
                weight = 3
            [[languages.en.menus.main]]
                name = "Now"
                url = "/en/now/"
                weight = 4
        [languages.it]
            contentDir = "content/it"
            disabled = false
            languageCode = "it-IT"
            languageDirection = "ltr"
            languageName = "Italian"
            title = "Matteo Cervelli"
            weight = 2
            [languages.it.params]
                subtitle = "Ingegnere della Crescita delle Imprese"
            [languages.it.menus]
                [[languages.it.menus.main]]
                    name = "Su di me"
                    url = "/it/about/"
                    weight = 1
                [[languages.it.menus.main]]
                    name = "Articoli"
                    url = "/it/posts/"
                    weight = 2
                [[languages.it.menus.main]]
                    name = "Lavoro"
                    url = "/it/lavora-con-me/"
                    weight = 3
                [[languages.it.menus.main]]
                    name = "Ora"
                    url = "/it/ora/"
                    weight = 4
[params]
    custom_css = ["css/styles.css"]
    author = "Matteo Cervelli"
    dateFormat = "2 January 2006"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
[permalinks] 
    posts = "/:slug"
[taxonomies]
    tag = 'tags'
    category = 'categories'
[frontmatter]
  [frontmatter.default]
    # Per tutti i contenuti in content/posts
    [frontmatter.default.posts]
      sidebar = true
    
    # Per tutti i contenuti singoli che non sono home o sezioni
    [frontmatter.default.pages]
      sidebar = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"