[build]
  publish = "public"
  command = "hugo --gc --minify --cleanDestinationDir --environment production"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.140.2"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/*/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

# Force WWW and HTTP to HTTPS non-WWW
[[redirects]]
  from = "https://www.matteocervelli.com/*"
  to = "https://matteocervelli.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.matteocervelli.com/*"
  to = "https://matteocervelli.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://matteocervelli.com/*"
  to = "https://matteocervelli.com/:splat"
  status = 301
  force = true

# Static assets should bypass language redirects
[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

# Direct language paths should never be redirected elsewhere
[[redirects]]
  from = "/it/*"
  to = "/it/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200
  force = true

# Old essays redirects
[[redirects]]
  from = "/essays/the-purple-cow/*"
  to = "/en/the-purple-cow"
  status = 301
  force = true

[[redirects]]
  from = "/essays/the-people-garden-manifesto/*"
  to = "/en/the-people-garden-manifesto"
  status = 301
  force = true

[[redirects]]
  from = "/essays/fake-purpose-undermines-company-success/*"
  to = "/en/fake-purpose-undermines-company-success"
  status = 301
  force = true

# Language-specific 404 pages
[[redirects]]
  from = "/it/404"
  to = "/it/404.html"
  status = 404

[[redirects]]
  from = "/en/404"
  to = "/en/404.html"
  status = 404

# Root path redirect based on browser language
[[redirects]]
  from = "/"
  to = "/it/"
  status = 302
  conditions = {Language = ["it-IT", "it"]}
  force = true

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302
  force = true

# Final catch-all redirect for unknown paths
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/en/feed"
  to = "/en/feed.xml"
  status = 200
  force = true

[[redirects]]
  from = "/en/feed/"
  to = "/en/feed.xml"
  status = 200
  force = true

[[redirects]]
  from = "/it/feed"
  to = "/it/feed.xml"
  status = 200
  force = true

[[redirects]]
  from = "/it/feed/"
  to = "/it/feed.xml"
  status = 200
  force = true

[[headers]]
  for = "/*/feed.xml"
  [headers.values]
    Content-Type = "application/rss+xml; charset=utf-8"

[[redirects]]
  from = "/*/legal/*"
  to = "/*/legal/:splat.html"
  status = 200
  force = true

# API redirects for serverless functions
[[redirects]]
  from = "/api/resend-confirmation"
  to = "/.netlify/functions/resend-confirmation"
  status = 200
  force = true