[build]
  publish = "public"
  command = "hugo --gc --minify --cleanDestinationDir --environment production"

[build.environment]
  HUGO_VERSION = "0.140.2"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/*/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

[[redirects]]
  from = "/essays/the-purple-cow/*"
  to = "/en/the-purple-cow"
  status = 301
  force = true

[[redirects]]
  from = "/essays/the-people-garden-manifesto/*"
  to = "/en/the-people-garden-manifesto"
  status = 301
  force = true

[[redirects]]
  from = "/essays/fake-purpose-undermines-company-success/*"
  to = "/en/fake-purpose-undermines-company-success"
  status = 301
  force = true

[[redirects]]
  from = "/it/*"
  to = "/it/404.html"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/en/404.html"
  status = 404